# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

gems: [jekyll-paginate]
paginate_path: "page:num" 
# Setup
title:               A Persistnt Existence
tagline:             'deep-guy's blog'
description:         'A blog site made by Deep Inder Mohan, student at IIIT Bangalore' 
url:                 https://github.com/deep-guy/
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
